name: 'ccodwg-update-run'
description: 'Run commands in the ccodwg-update Docker container'
inputs:
  command_string:
    description: 'Command string to run in the Docker container'
    required: true
  service_key:
    description: 'Google service account key'
    required: true
  gh_pat:
    description: 'GitHub personal access token'
    required: true
  docker_token:
    description: 'GitHub PAT for accessing the GHCR'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run commands in Docker container
      run: |
        echo $TOKEN | docker login ghcr.io -u jeanpaulrsoucy --password-stdin
        docker pull selenium/standalone-chrome:latest
        docker pull ghcr.io/ccodwg/ccodwg-update:latest
        docker run --rm -e SERVICE_KEY -e GH_PAT -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/ccodwg/ccodwg-update:latest /bin/bash -c "${{ inputs.command_string }}"
      shell: bash
      env:
        SERVICE_KEY: ${{ inputs.service_key }}
        GH_PAT: ${{ inputs.gh_pat }}
        TOKEN: ${{ inputs.docker_token }}
