name: 'ccodwg-archive-run'
description: 'Run commands in the ccodwg-archive Docker container'
inputs:
  command_string:
    description: 'Command string to run in the Docker container'
    required: true
  archive_env:
    description: 'Environmental variables for the archival scripts'
    required: true
  docker_token:
    description: 'GitHub PAT for accessing the GHCR'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run commands in Docker container
      run: |
        echo $TOKEN | docker login ghcr.io -u jeanpaulrsoucy --password-stdin
        docker pull ghcr.io/ccodwg/ccodwg-archive:main
        docker run --rm -t -e ARCHIVE_ENV -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/ccodwg/ccodwg-archive:main /bin/bash -c "${{ inputs.command_string }}"
      shell: bash
      env:
        ARCHIVE_ENV: ${{ inputs.archive_env }}
        TOKEN: ${{ inputs.docker_token }}
