name: 'send-email'
description: 'Send email'
inputs:
  subject:
    description: Email subject
    required: true
  body:
    description: Email body
    required: true
  archive_env:
    description: 'Environmental variables for the archival scripts'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send email
      run: |
        echo "$ARCHIVE_ENV" >> ~/archive.env
        set -a; source ~/archive.env; set +a
        export SUBJECT="${{ inputs.subject }}"
        export BODY="${{ inputs.body }}"
        python - <<EOF
        import os
        import smtplib
        from email.mime.text import MIMEText
        sender = (os.environ['MAIL_ALIAS'] if 'MAIL_ALIAS' in os.environ.keys() else os.environ['MAIL_NAME'])
        to = os.environ['MAIL_TO']
        msg = MIMEText(os.environ['BODY'].encode('utf-8'), _charset='utf-8')
        msg['Subject'] = os.environ['SUBJECT']
        msg['From'] = sender
        msg['To'] = to
        server = smtplib.SMTP_SSL(os.environ['SMTP_SERVER'], os.environ['SMTP_PORT'])
        server.ehlo()
        server.login(os.environ['MAIL_NAME'], os.environ['MAIL_PASS'])
        server.sendmail(sender, to, msg.as_string())
        server.close()
        EOF
      shell: bash
      env:
        ARCHIVE_ENV: ${{ inputs.archive_env }}
