name: 'send-email'
description: 'Send email'
inputs:
  subject:
    description: Email subject
    required: true
  body:
    description: Email body (Base64 encoded)
    required: true
  to:
    description: Email account receiving the message
    required: true
  from:
    description: Email account sending the message
    required: true
  from_alias:
    description: (Optional) Alias name of the sender's email account
    required: false
  mail_pass:
    description: Password of the sender's email account 
    required: true
  smtp_server:
    description: SMTP server address
    required: true
  smtp_port:
    description: SMTP server port
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Send email
      run: |
        export SUBJECT="${{ inputs.subject }}"
        export BODY=$(echo "${{ inputs.body }}" | base64 --decode)
        export MAIL_TO="${{ inputs.to }}"
        export MAIL_NAME="${{ inputs.from }}"
        export MAIL_ALIAS="${{ inputs.from_alias }}"
        if [[ $MAIL_ALIAS == "" ]]
        then
          MAIL_ALIAS=$MAIL_NAME
        fi
        export MAIL_PASS="${{ inputs.mail_pass }}"
        export SMTP_SERVER="${{ inputs.smtp_server }}"
        export SMTP_PORT="${{ inputs.smtp_port }}"
        python - <<EOF
        import os
        import smtplib
        from email.mime.text import MIMEText
        sender = os.environ['MAIL_ALIAS']
        to = os.environ['MAIL_TO']
        msg = MIMEText(os.environ['BODY'].encode('utf-8'), _charset='utf-8')
        msg['Subject'] = os.environ['SUBJECT']
        msg['From'] = sender
        msg['To'] = to
        server = smtplib.SMTP_SSL(os.environ['SMTP_SERVER'], os.environ['SMTP_PORT'])
        server.ehlo()
        server.login(os.environ['MAIL_NAME'], os.environ['MAIL_PASS'])
        server.sendmail(sender, to, msg.as_string())
        server.close()
        EOF
      shell: bash
