name: ccodwg-update-verify-manual-data

on:
  workflow_dispatch

jobs:
  run-update-nightly:
    runs-on: ubuntu-latest
    name: Verify if manual data required for CCODWG nightly update has been inputed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands in Docker container
        uses: ./actions/ccodwg-update-run
        with:
          command_string: "scripts/copy-service-key.sh; scripts/verify-manual-data.sh"
          gh_pat: ${{ secrets.gh_pat }}
          service_key: ${{ secrets.service_key }}
