name: ccodwg-update

on:
  workflow_dispatch

jobs:
  run-update-nightly:
    runs-on: ubuntu-latest
    name: Update CovidTimelineCanada
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands in Docker container
        uses: ./actions/ccodwg-update-run
        with:
          command_string: "export GITHUB_PAT=$GH_PAT; \
                           scripts/copy-service-key.sh; \
                           scripts/update-data.sh; \
                           scripts/update-plots.sh"
          service_key: ${{ secrets.service_key }}
          gh_pat: ${{ secrets.gh_pat }}
          docker_token: ${{ secrets.gh_pat_docker }}
