name: ccodwg-update-nightly

on:
  workflow_dispatch

jobs:
  run-update-nightly:
    runs-on: ubuntu-latest
    name: Run final CCODWG update (main); push nightly CCODWG data update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands in Docker container
        uses: ./actions/ccodwg-update-run
        with:
          command_string: "export GITHUB_PAT=$GH_PAT; \
                           scripts/copy-service-key.sh; \
                           scripts/update-main.sh; \
                           scripts/update-nightly.sh"
          gh_pat: ${{ secrets.gh_pat }}
          service_key: ${{ secrets.service_key }}
