name: ccodwg-update-validate-only

on:
  workflow_dispatch

jobs:
  run-update-nightly:
    runs-on: ubuntu-latest
    name: Perform dry run of CCODWG nightly update (stop after sending validation results)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run commands in Docker container
        uses: ./actions/ccodwg-update-run
        with:
          command_string: "export GITHUB_PAT=$GH_PAT; \
                           scripts/copy-service-key.sh; \
                           scripts/verify-data-sources.sh; \
                           cd /; rm -rf Covid19Canada; \
                           export CCODWG_STATUS=NO_UPDATE; \
                           scripts/update-nightly.sh"
          gh_pat: ${{ secrets.gh_pat }}
          service_key: ${{ secrets.service_key }}
