name: "Docker image: ccodwg-update"

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  CONTEXT: docker/ccodwg-update
  IMAGE: ghcr.io/ccodwg/ccodwg-update:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_DOCKER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT }}
          push: true
          tags: ${{ env.IMAGE }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"