name: pushover

on:
  workflow_dispatch:
    inputs:
      message:
        description: "The body of the notification"
        required: true
      priority:
        description: "Message priority, an integer from -2 to 2, see: https://pushover.net/api#priority; defaults to 0 (normal priority)"
        required: true
        default: 0
      title:
        description: "The title of the notification; if not provided, the application's name will be used"
        required: false
      device:
        description: "The name of the device to send the notification to; if not provided, the notification will be sent to all devices"
        required: false

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: Pushover
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read and set Pushover environment
        run: |
          # set and mask variables from Pushover environment file
          export $(echo "$PO_ENV")
          echo "po_key=$PO_KEY" >> $GITHUB_ENV; echo "::add-mask::$PO_KEY"
          echo "po_token=$PO_TOKEN" >> $GITHUB_ENV; echo "::add-mask::$PO_TOKEN"
        shell: bash
        env:
          PO_ENV: ${{ secrets.po_env }}
      - name: Pushover
        uses: ./actions/pushover
        with:
          message: ${{ github.event.inputs.message }}
          priority: ${{ github.event.inputs.priority }}
          title: ${{ github.event.inputs.title }}
          device: ${{ github.event.inputs.device }}
          po_key: ${{ env.po_key }}
          po_token: ${{ env.po_token }}
