name: send-email

on:
  workflow_dispatch:
    inputs:
      to:
        description: The email address the message with be sent to (if not provided, will be read from environmental variable MAIL_TO)
        required: false
      subject:
        description: Email subject
        required: true
      body:
        description: Email body
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    name: Send email
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send email
        uses: ./actions/send-email
        with:
          to: ${{ github.event.inputs.to }}
          subject: ${{ github.event.inputs.subject }}
          body: ${{ github.event.inputs.body }}
          archive_env: ${{ secrets.archive_env }}
